### PR TITLE
feat: Implementation of basic box-model widgets.

### PR DESCRIPTION
**Pull request by xanahopper**
## Widgets
- `ConstrainedBox`
- `UncontrainedBox`
- `ColoredBox`
- `SizedBox`

## Traits
- ~~`BoxLayoutWidget`, common for box-model measure and layout~~
- `ChildWidget`, widgets with children.

### CODE REVIEW

**Comment by toiglak** [comment]
Sorry to keep you waiting.

You added the `BoxLayoutWidget` trait, but we lay out widgets using “box constraints'' by default in Frui. You can see this in the `layout` method of `RenderWidget` which takes the `Constraints` argument – the same as in `RenderBox` in Flutter. 

As for the `compute_max_intrinsic_width` method and the similar, I think we can add them directly to the `RenderWidget`. Alternatively (and I really would like to try this option out) we could implement the [`measure`](https://github.com/linebender/druid/blob/20d11542a302606a7b381e841f036ec13812800f/xilem/src/widget.rs#L55) method from `Xilem`, which seems to do the exact thing we need here!

**Comment by xanahopper** [comment]
Yes, adding to`RenderWidget` directly and splitting the layout into measure and layout are considered.
`BoxLayoutWidget` is declared because I want to keep a position for the Scrolling/Sliver model, but now it seems unnecessary.

And I'm trying some patterns to simulate the OOP abstraction design and defined some default behaviors that can be overridden, but I think it's not suitable for Rust.

I'll change these directly to `RenderWidget` later in this PR.

**Comment by xanahopper** [comment]
@toiglak `BoxLayoutWidget` has been removed, and methods in this move to `RenderWidget` with the default implementation.

**Comment by xanahopper** [comment]
Flex PR #9 is based on this.

**Pull request closed without merging**
